version: '3.1'

services:

  web:
    build: ./docker/web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - .:/var/www/html/
    ports:
      - 8088:80
    working_dir: /var/www/html/

  composer:
    image: composer:1.6
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    command: composer update --ignore-platform-reqs

  mysql:
    image: mysql:5.7
    restart: ${MYSQL_RESTART}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
